
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: questloop
      POSTGRES_PASSWORD: questloop
      POSTGRES_DB: questloop
    volumes: [ "db_data:/var/lib/postgresql/data" ]
  redis:
    image: redis:7-alpine
  api:
    build: ./api
    depends_on: [ db, redis ]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      JWT_SECRET: ${JWT_SECRET}
      PUBLIC_WEB_URL: ${PUBLIC_WEB_URL}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      VAPID_SUBJECT: ${VAPID_SUBJECT}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
  web:
    build: ./web
    environment:
      NEXT_PUBLIC_API_URL: "https://api.${DOMAIN}"
    depends_on: [ api ]
  caddy:
    image: caddy:2
    ports: [ "80:80", "443:443" ]
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${ACME_EMAIL}
volumes:
  db_data:
  caddy_data:
  caddy_config:
