
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: questloop
      POSTGRES_PASSWORD: questloop
      POSTGRES_DB: questloop
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
  api:
    build: ./api
    depends_on:
      - db
      - redis
      - mailpit
    environment:
      DATABASE_URL: postgresql://questloop:questloop@db:5432/questloop?schema=public
      REDIS_URL: redis://redis:6379
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASS: ""
      EMAIL_FROM: "no-reply@questloop.local"
      JWT_SECRET: "dev_dev_dev_change_me"
      PUBLIC_WEB_URL: "http://localhost:3000"
      NODE_ENV: "development"
    ports:
      - "4000:4000"
    command: sh -c "npx prisma migrate deploy && npm run start:docker"
  web:
    build: ./web
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
    ports:
      - "3000:3000"
volumes:
  db_data:
